name: Build project using muddler and upload artifact

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Muddle
        uses: demonnic/build-with-muddler@main
        with:
          muddlerVersion: LATEST
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Iniquity
          path: build/tmp/
